'use client'
import { useEffect, useMemo, useState } from 'react'
import { Calendar, ChevronRight, Crown, Download, Phone, Search, TrendingUp, Users, X } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'
import { currentRestaurantTenant } from '@/lib/restaurant'

type Order={id:string;order_number:number;customer_name:string|null;customer_phone:string;total:number;payment_status:string;payment_method:string|null;created_at:string;restaurant_tables:{table_number:string}|null;restaurant_order_items:{item_name:string;quantity:number}[]}
type Customer={name:string;phone:string;orders:number;spent:number;last:string;history:Order[]}
const money=(n:number)=>`₹${Number(n).toLocaleString('en-IN',{maximumFractionDigits:2})}`
const segment=(c:Customer)=>c.spent>=500||c.orders>=3?'vip':c.orders===2?'regular':'new'

export function RestaurantCustomers(){
 const [customers,setCustomers]=useState<Customer[]|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[selected,setSelected]=useState<Customer|null>(null)
 useEffect(()=>{const load=async()=>{try{const tenant=await currentRestaurantTenant(),db=createClient();const{data,error}=await db.from('restaurant_orders').select('id,order_number,customer_name,customer_phone,total,payment_status,payment_method,created_at,restaurant_tables(table_number),restaurant_order_items(item_name,quantity)').eq('tenant_id',tenant).not('customer_phone','is',null).order('created_at',{ascending:false});if(error)throw error;const map=new Map<string,Customer>();((data??[]) as unknown as Order[]).forEach((raw:Order)=>{const c=map.get(raw.customer_phone)||{name:raw.customer_name||'Guest',phone:raw.customer_phone,orders:0,spent:0,last:raw.created_at,history:[]};c.name=c.name==='Guest'&&raw.customer_name?raw.customer_name:c.name;c.orders++;c.spent+=Number(raw.total);c.last=c.last>raw.created_at?c.last:raw.created_at;c.history.push(raw);map.set(raw.customer_phone,c)});setCustomers([...map.values()].sort((a,b)=>b.spent-a.spent))}catch(e){setError(e instanceof Error?e.message:'Unable to load customer CRM')}};void load()},[])
 const visible=useMemo(()=>{return(customers??[]).filter(c=>{const matches=`${c.name} ${c.phone}`.toLowerCase().includes(query.toLowerCase());const recent=Date.now()-new Date(c.last).getTime()<604800000;const matchesFilter=filter==='all'||filter==='vip'&&segment(c)==='vip'||filter==='repeat'&&c.orders>=2||filter==='recent'&&recent;return matches&&matchesFilter})},[customers,query,filter])
 if(!customers)return <div className="rounded-2xl border border-dashed p-10 text-center text-muted-foreground">{error||'Loading customer CRM…'}</div>
 const revenue=customers.reduce((n,c)=>n+c.spent,0)
 const exportCsv=()=>{const quote=(value:string|number)=>`"${String(value).replaceAll('"','""')}"`;const rows=['Customer Name,Phone Number,Total Orders,Total Spent,Last Visit Date',...visible.map(c=>[quote(c.name),quote(c.phone),c.orders,c.spent,quote(new Date(c.last).toLocaleString('en-IN'))].join(','))];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv'}));a.download='rvc-customers.csv';a.click()}
 return <div className="space-y-6"><div><h2 className="text-3xl font-semibold">Customer CRM</h2><p className="mt-1 text-muted-foreground">Guest loyalty and spending from real QR orders.</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Total customers" value={customers.length} icon={<Users/>}/><Metric label="Repeat diners" value={customers.filter(c=>c.orders>1).length} icon={<TrendingUp/>}/><Metric label="Average lifetime value" value={money(customers.length?revenue/customers.length:0)} icon={<TrendingUp/>}/><Metric label="Top spender revenue" value={money(customers[0]?.spent||0)} icon={<Crown/>}/></div><section className="rounded-2xl border bg-card p-4"><div className="flex flex-wrap gap-3"><label className="relative min-w-52 flex-1"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name or phone…" className="w-full rounded-xl border bg-background py-2 pl-9"/></label><button onClick={exportCsv} className="rounded-xl border px-4 py-2 text-sm"><Download className="mr-1 inline size-4"/>Export customer list</button></div><div className="mt-3 flex gap-2 overflow-x-auto">{[['all','All Guests'],['vip','VIP Spenders'],['repeat','Repeat Diners'],['recent','Recent']].map(([key,label])=><button key={key} onClick={()=>setFilter(key)} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-sm ${filter===key?'bg-primary text-primary-foreground':'bg-muted'}`}>{label}</button>)}</div></section><section className="overflow-x-auto rounded-2xl border bg-card"><table className="w-full min-w-[800px] text-sm"><thead className="bg-muted/50 text-left text-xs text-muted-foreground"><tr><th className="p-4">Customer</th><th>Phone</th><th>Orders</th><th>Lifetime spend</th><th>Segment</th><th>Last visit</th><th/></tr></thead><tbody>{visible.map(c=><tr key={c.phone} className="border-t"><td className="p-4"><span className="mr-3 inline-grid size-9 place-items-center rounded-full bg-primary/10 font-bold text-primary">{c.name[0]?.toUpperCase()}</span><b>{c.name}</b></td><td><Phone className="mr-1 inline size-3"/>{c.phone}</td><td>{c.orders} orders</td><td className="font-semibold">{money(c.spent)}</td><td><Badge customer={c}/></td><td>{new Date(c.last).toLocaleString('en-IN')}</td><td><button onClick={()=>setSelected(c)} className="inline-flex items-center text-primary">View history <ChevronRight size={16}/></button></td></tr>)}</tbody></table>{!visible.length&&<p className="p-10 text-center text-muted-foreground">No matching customers.</p>}</section>{selected&&<Drawer customer={selected} onClose={()=>setSelected(null)}/>}</div>
}
function Metric({label,value,icon}:{label:string;value:string|number;icon:React.ReactNode}){return <article className="rounded-2xl border bg-card p-4"><span className="text-primary">{icon}</span><p className="mt-3 text-sm text-muted-foreground">{label}</p><b className="mt-1 block text-2xl">{value}</b></article>}
function Badge({customer}:{customer:Customer}){const value=segment(customer);return <span className={`rounded-full px-2 py-1 text-xs ${value==='vip'?'bg-amber-100 text-amber-700':value==='regular'?'bg-blue-100 text-blue-700':'bg-emerald-100 text-emerald-700'}`}>{value==='vip'?'👑 VIP Guest':value==='regular'?'🔄 Regular':'🌱 New Guest'}</span>}
function Drawer({customer,onClose}:{customer:Customer;onClose:()=>void}){return <div className="fixed inset-0 z-[80] flex justify-end bg-black/50" onClick={onClose}><aside onClick={e=>e.stopPropagation()} className="h-full w-full max-w-lg overflow-y-auto bg-card p-6 shadow-2xl"><button onClick={onClose} className="float-right"><X/></button><h2 className="text-2xl font-bold">{customer.name}</h2><p className="mt-1 text-muted-foreground"><Phone className="mr-1 inline size-4"/>{customer.phone}</p><div className="mt-5 flex justify-between rounded-2xl bg-muted/50 p-4"><span>Total spend <b className="block">{money(customer.spent)}</b></span><Badge customer={customer}/></div><h3 className="mt-6 font-semibold">Order history</h3><div className="mt-3 space-y-3">{customer.history.map(o=><article key={o.id} className="rounded-2xl border p-4"><div className="flex justify-between"><b>Order #{o.order_number}</b><span className={o.payment_status==='paid'?'text-emerald-600':'text-amber-600'}>{o.payment_status==='paid'?`Paid · ${o.payment_method||'—'}`:'Unpaid'}</span></div><p className="mt-2 text-sm"><Calendar className="mr-1 inline size-4"/>{new Date(o.created_at).toLocaleString('en-IN')} · Table {o.restaurant_tables?.table_number||'—'}</p><p className="mt-2 text-sm text-muted-foreground">{o.restaurant_order_items.map(i=>`${i.item_name} ×${i.quantity}`).join(', ')}</p><b className="mt-3 block">{money(o.total)}</b></article>)}</div></aside></div>}
