'use client'

import { useEffect, useMemo, useState } from 'react'
import { Building2, Eye, RefreshCw, Search, ShieldAlert, X } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

type Status='trial'|'active'|'past_due'|'expired'|'suspended'
type Tenant={id:string;name:string;slug:string;vertical:string;status:Status;subscription_status:Status|null;subscription_expires_at:string|null;subscription_end_date:string|null;plan_id:string|null;created_at:string;owner_id:string|null;saas_plans:{name:string}|null}
type Plan={id:string;name:string;price_monthly:number;price_yearly:number}
type Profile={id:string;tenant_id:string|null;full_name:string|null;phone:string|null}
const styles:Record<Status,string>={active:'bg-emerald-500/10 text-emerald-600',trial:'bg-amber-500/15 text-amber-600',past_due:'bg-orange-500/10 text-orange-600',expired:'bg-red-500/10 text-red-500',suspended:'bg-red-500/10 text-red-500'}
const currentStatus=(tenant:Tenant)=>(tenant.subscription_status||tenant.status) as Status
const asInputDate=(value:string|null)=>value?new Date(value).toISOString().slice(0,16):''

export default function TenantsPage(){
 const db=createClient(),[tenants,setTenants]=useState<Tenant[]>([]),[plans,setPlans]=useState<Plan[]>([]),[owners,setOwners]=useState<Record<string,Profile>>({}),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[selected,setSelected]=useState<Tenant|null>(null),[loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[error,setError]=useState('')
 const load=async()=>{setLoading(true);const[{data:tenantData,error:tenantError},{data:planData},{data:profileData}]=await Promise.all([db.from('tenants').select('*,saas_plans(name)').order('created_at',{ascending:false}),db.from('saas_plans').select('id,name,price_monthly,price_yearly').order('price_monthly'),db.from('profiles').select('id,tenant_id,full_name,phone').eq('role','tenant_owner')]);setError(tenantError?.message||'');setTenants((tenantData??[])as Tenant[]);setPlans((planData??[])as Plan[]);setOwners(Object.fromEntries((profileData??[]).filter(p=>p.tenant_id).map(p=>[p.tenant_id!,p as Profile])));setLoading(false)}
 useEffect(()=>{void load()},[])
 const filtered=useMemo(()=>tenants.filter(tenant=>(status==='all'||currentStatus(tenant)===status)&&`${tenant.name} ${tenant.slug} ${tenant.vertical} ${owners[tenant.id]?.full_name||''}`.toLowerCase().includes(query.toLowerCase())),[tenants,status,query,owners])
 const save=async(tenant:Tenant,form:{planId:string;status:Status;expires:string})=>{const expires=form.expires?new Date(form.expires).toISOString():null;const{error:rpcError}=await db.rpc('admin_update_tenant_subscription',{p_tenant_id:tenant.id,p_plan_id:form.planId||null,p_status:form.status,p_expires_at:expires});if(rpcError){setError(rpcError.message);return false}setNotice(`${tenant.name} subscription updated.`);setSelected(null);void load();return true}
 return <div className="space-y-7"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-primary">Workspace / Tenants</p><h1 className="mt-1 text-3xl font-bold">Business accounts</h1><p className="mt-2 text-sm text-muted-foreground">Set plans, exact expiry times, and account access.</p></div><button onClick={()=>void load()} className="inline-flex items-center gap-2 rounded-xl border bg-card px-4 py-2.5 text-sm font-semibold"><RefreshCw className={`size-4 ${loading?'animate-spin':''}`}/>Refresh</button></div>{notice&&<p className="rounded-xl bg-emerald-500/10 px-4 py-3 text-sm text-emerald-600">{notice}</p>}{error&&<p className="rounded-xl bg-red-500/10 px-4 py-3 text-sm text-red-500">{error}</p>}<section className="overflow-hidden rounded-2xl border bg-card"><div className="flex gap-3 border-b p-4"><label className="relative flex-1"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search business or owner…" className="h-10 w-full rounded-xl border bg-background pl-10 pr-3 text-sm"/></label><select value={status} onChange={e=>setStatus(e.target.value)} className="h-10 rounded-xl border bg-background px-3 text-sm"><option value="all">All statuses</option>{Object.keys(styles).map(value=><option key={value}>{value}</option>)}</select></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-muted/40 text-xs uppercase text-muted-foreground"><tr><th className="px-5 py-4">Business</th><th className="px-5 py-4">Plan</th><th className="px-5 py-4">Subscription</th><th className="px-5 py-4">Expiry</th><th className="px-5 py-4">Owner</th><th/></tr></thead><tbody>{filtered.map(tenant=>{const subscription=currentStatus(tenant),expiry=tenant.subscription_expires_at||tenant.subscription_end_date;return <tr key={tenant.id} className="border-t hover:bg-muted/30"><td className="px-5 py-4"><b>{tenant.name}</b><small className="block text-muted-foreground">{tenant.slug}</small></td><td className="px-5 py-4">{tenant.saas_plans?.name||'No plan'}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${styles[subscription]}`}>{subscription}</span></td><td className="px-5 py-4 text-muted-foreground">{expiry?new Date(expiry).toLocaleString('en-IN'):'Not set'}</td><td className="px-5 py-4">{owners[tenant.id]?.full_name||'Not assigned'}</td><td className="px-5 py-4 text-right"><button onClick={()=>setSelected(tenant)} className="rounded-lg p-2 text-primary hover:bg-primary/10"><Eye className="size-4"/></button></td></tr>})}</tbody></table></div>{!loading&&!filtered.length&&<p className="p-10 text-center text-sm text-muted-foreground">No businesses found.</p>}</section>{selected&&<SubscriptionDrawer tenant={selected} plans={plans} owner={owners[selected.id]} onClose={()=>setSelected(null)} onSave={save}/>}</div>
}
function SubscriptionDrawer({tenant,plans,owner,onClose,onSave}:{tenant:Tenant;plans:Plan[];owner?:Profile;onClose:()=>void;onSave:(tenant:Tenant,form:{planId:string;status:Status;expires:string})=>Promise<boolean>}){const[planId,setPlanId]=useState(tenant.plan_id||''),[status,setStatus]=useState<Status>(currentStatus(tenant)),[expires,setExpires]=useState(asInputDate(tenant.subscription_expires_at||tenant.subscription_end_date)),[saving,setSaving]=useState(false);const submit=async()=>{setSaving(true);await onSave(tenant,{planId,status,expires});setSaving(false)};return <div className="fixed inset-0 z-[60] flex justify-end bg-slate-950/50" onClick={onClose}><aside onClick={e=>e.stopPropagation()} className="h-full w-full max-w-md overflow-y-auto border-l bg-card p-6 shadow-2xl"><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-xl bg-primary/10 text-primary"><Building2/></span><button onClick={onClose}><X/></button></div><h2 className="mt-6 text-2xl font-bold">{tenant.name}</h2><p className="mt-1 text-sm text-muted-foreground">{owner?.full_name||'Owner not assigned'} · {tenant.slug}</p><div className="mt-6 space-y-4"><label className="block text-sm font-medium">Plan<select value={planId} onChange={e=>setPlanId(e.target.value)} className="mt-1 w-full rounded-xl border bg-background p-3"><option value="">No plan</option>{plans.map(plan=><option key={plan.id} value={plan.id}>{plan.name} · ₹{plan.price_monthly}/month</option>)}</select></label><label className="block text-sm font-medium">Subscription status<select value={status} onChange={e=>setStatus(e.target.value as Status)} className="mt-1 w-full rounded-xl border bg-background p-3">{(['trial','active','past_due','expired','suspended']as Status[]).map(value=><option key={value} value={value}>{value}</option>)}</select></label><label className="block text-sm font-medium">Exact expiry date and time<input type="datetime-local" value={expires} onChange={e=>setExpires(e.target.value)} className="mt-1 w-full rounded-xl border bg-background p-3"/></label><div className="grid grid-cols-2 gap-2"><button onClick={()=>setExpires(new Date(Date.now()+30*86400000).toISOString().slice(0,16))} className="rounded-xl border py-2 text-sm">Extend 30 days</button><button onClick={()=>{setStatus('expired');setExpires(new Date().toISOString().slice(0,16))}} className="rounded-xl border border-red-200 py-2 text-sm text-red-600">Force expire</button></div><button onClick={()=>setStatus('suspended')} className="flex w-full items-center justify-center gap-2 rounded-xl bg-red-500 py-3 text-sm font-semibold text-white"><ShieldAlert className="size-4"/>Freeze account</button><button disabled={saving} onClick={submit} className="w-full rounded-xl bg-primary py-3 font-semibold text-primary-foreground">{saving?'Saving…':'Save subscription changes'}</button></div></aside></div>}
