'use client'

import { useMemo, useState } from 'react'
import { motion } from 'framer-motion'
import { ArrowUpRight, Building2, CircleDollarSign, Clock3, MoreHorizontal, ShieldCheck, Users } from 'lucide-react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

const revenue30 = [
  { label: '01 Jun', value: 124000 }, { label: '05 Jun', value: 138000 }, { label: '10 Jun', value: 132000 }, { label: '15 Jun', value: 152000 }, { label: '20 Jun', value: 168000 }, { label: '25 Jun', value: 178000 }, { label: '30 Jun', value: 194000 },
]
const revenue90 = [
  { label: 'Apr', value: 310000 }, { label: 'May', value: 420000 }, { label: 'Jun', value: 520000 },
]
const verticals = [{ name: 'Restaurant', value: 428 }, { name: 'School', value: 236 }, { name: 'Hospital', value: 174 }, { name: 'Gym', value: 128 }, { name: 'Retail', value: 92 }]
const cityData = [{ city: 'Indore', tenants: 84, revenue: 'INR 9.4L' }, { city: 'Jaipur', tenants: 71, revenue: 'INR 8.1L' }, { city: 'Lucknow', tenants: 63, revenue: 'INR 7.5L' }, { city: 'Nagpur', tenants: 48, revenue: 'INR 5.9L' }, { city: 'Coimbatore', tenants: 39, revenue: 'INR 4.8L' }]
const statusData = [{ name: 'Active', value: 842, color: '#4338ca' }, { name: 'Trial', value: 128, color: '#f59e0b' }, { name: 'At risk', value: 36, color: '#ef4444' }]

function Metric({ label, value, change, icon: Icon, accent }: { label: string; value: string; change: string; icon: typeof Building2; accent: string }) {
  return <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="rounded-2xl border border-border bg-card p-5 shadow-sm">
    <div className="flex items-start justify-between"><span className={`grid size-10 place-items-center rounded-xl ${accent}`}><Icon className="size-5" /></span><span className="inline-flex items-center gap-1 text-xs font-semibold text-emerald-500"><ArrowUpRight className="size-3.5" />{change}</span></div>
    <p className="mt-5 text-sm text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">{value}</p>
  </motion.div>
}

export default function AdminDashboardPage() {
  const [range, setRange] = useState<'30' | '90'>('30')
  const chartData = useMemo(() => range === '30' ? revenue30 : revenue90, [range])
  return <div className="space-y-8">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-primary">Monday, 30 June 2025</p><h1 className="mt-1 text-3xl font-bold tracking-tight sm:text-4xl">Good morning, Arjun.</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Here is the operating pulse across the RVC platform.</p></div><div className="flex items-center gap-2 rounded-xl border border-border bg-card p-1"><button type="button" onClick={() => setRange('30')} className={`rounded-lg px-3 py-2 text-xs font-semibold ${range === '30' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground'}`}>30 days</button><button type="button" onClick={() => setRange('90')} className={`rounded-lg px-3 py-2 text-xs font-semibold ${range === '90' ? 'bg-primary text-primary-foreground' : 'text-muted-foreground'}`}>90 days</button></div></div>

    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Monthly recurring revenue" value="INR 52.4L" change="12.8%" icon={CircleDollarSign} accent="bg-primary/15 text-primary" /><Metric label="Active tenants" value="842" change="8.4%" icon={Building2} accent="bg-accent/20 text-accent-foreground" /><Metric label="Platform users" value="18,904" change="16.2%" icon={Users} accent="bg-emerald-500/15 text-emerald-500" /><Metric label="Uptime this month" value="99.98%" change="0.04%" icon={ShieldCheck} accent="bg-violet-500/15 text-violet-500" /></div>

    <div className="grid gap-6 xl:grid-cols-[1.6fr_1fr]"><section className="rounded-2xl border border-border bg-card p-5 sm:p-6"><div className="mb-6 flex items-start justify-between"><div><p className="text-sm font-semibold">Platform revenue</p><p className="mt-1 text-xs text-muted-foreground">Gross recurring revenue across all verticals</p></div><button type="button" className="rounded-lg p-2 text-muted-foreground hover:bg-muted"><MoreHorizontal className="size-5" /></button></div><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4338ca" stopOpacity={0.34} /><stop offset="100%" stopColor="#4338ca" stopOpacity={0.02} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--border)" /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: 'var(--muted-foreground)', fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: 'var(--muted-foreground)', fontSize: 11 }} tickFormatter={(value) => `INR ${Math.round(value / 1000)}k`} /><Tooltip contentStyle={{ background: 'var(--card)', border: '1px solid var(--border)', borderRadius: 12, color: 'var(--foreground)' }} formatter={(value) => [`INR ${Number(value ?? 0).toLocaleString('en-IN')}`, 'Revenue']} /><Area type="monotone" dataKey="value" stroke="#4338ca" strokeWidth={3} fill="url(#revenueFill)" /></AreaChart></ResponsiveContainer></div></section><section className="rounded-2xl border border-border bg-card p-5 sm:p-6"><div className="mb-5"><p className="text-sm font-semibold">Tenant health</p><p className="mt-1 text-xs text-muted-foreground">Current account distribution</p></div><div className="h-52"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={statusData} dataKey="value" nameKey="name" innerRadius={55} outerRadius={78} paddingAngle={4}>{statusData.map((entry) => <Cell key={entry.name} fill={entry.color} />)}</Pie><Tooltip contentStyle={{ background: 'var(--card)', border: '1px solid var(--border)', borderRadius: 12 }} /></PieChart></ResponsiveContainer></div><div className="space-y-3">{statusData.map((entry) => <div key={entry.name} className="flex items-center justify-between text-sm"><span className="flex items-center gap-2"><span className="size-2 rounded-full" style={{ backgroundColor: entry.color }} />{entry.name}</span><span className="font-semibold">{entry.value}</span></div>)}</div></section></div>

    <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-2xl border border-border bg-card p-5 sm:p-6"><div className="mb-6"><p className="text-sm font-semibold">Adoption by vertical</p><p className="mt-1 text-xs text-muted-foreground">Active tenants by product line</p></div><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={verticals} layout="vertical" margin={{ left: 8, right: 18 }}><CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="var(--border)" /><XAxis type="number" axisLine={false} tickLine={false} tick={{ fill: 'var(--muted-foreground)', fontSize: 11 }} /><YAxis dataKey="name" type="category" width={70} axisLine={false} tickLine={false} tick={{ fill: 'var(--muted-foreground)', fontSize: 11 }} /><Bar dataKey="value" fill="#4338ca" radius={[0, 6, 6, 0]} /></BarChart></ResponsiveContainer></div></section><section className="rounded-2xl border border-border bg-card p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-sm font-semibold">Top cities</p><p className="mt-1 text-xs text-muted-foreground">Revenue concentration by market</p></div><Clock3 className="size-5 text-muted-foreground" /></div><div className="overflow-x-auto"><table className="w-full min-w-[420px] text-left text-sm"><thead className="border-b border-border text-xs text-muted-foreground"><tr><th className="pb-3 font-medium">City</th><th className="pb-3 font-medium">Tenants</th><th className="pb-3 text-right font-medium">Revenue</th></tr></thead><tbody>{cityData.map((row, index) => <tr key={row.city} className="border-b border-border/60 last:border-0"><td className="py-4"><span className="mr-3 text-xs text-muted-foreground">0{index + 1}</span><span className="font-medium">{row.city}</span></td><td className="py-4 text-muted-foreground">{row.tenants}</td><td className="py-4 text-right font-semibold">{row.revenue}</td></tr>)}</tbody></table></div></section></div>

    <section className="rounded-2xl border border-border bg-card p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><p className="text-sm font-semibold">Live activity</p><p className="mt-1 text-xs text-muted-foreground">Latest events across the platform</p></div><span className="inline-flex items-center gap-2 rounded-full bg-emerald-500/10 px-3 py-1 text-xs font-semibold text-emerald-500"><span className="size-1.5 animate-pulse rounded-full bg-emerald-500" />Live</span></div><div className="grid gap-3 md:grid-cols-3"><ActivityItem title="New tenant activated" detail="Spice Route · Restaurant ERP" time="2 min ago" color="bg-emerald-500" /><ActivityItem title="Plan upgraded" detail="Bright Future Academy · Growth" time="18 min ago" color="bg-primary" /><ActivityItem title="Support ticket resolved" detail="MediCare Plus · Billing" time="42 min ago" color="bg-accent" /></div></section>
  </div>
}

function ActivityItem({ title, detail, time, color }: { title: string; detail: string; time: string; color: string }) { return <div className="flex items-start gap-3 rounded-xl bg-muted/40 p-4"><span className={`mt-1.5 size-2 shrink-0 rounded-full ${color}`} /><div className="min-w-0"><p className="text-sm font-semibold">{title}</p><p className="mt-1 truncate text-xs text-muted-foreground">{detail}</p><p className="mt-2 text-[11px] text-muted-foreground">{time}</p></div></div> }
