'use client'

import { useState } from 'react'
import { motion } from 'framer-motion'
import { Activity, Check, ChevronRight, Code2, CreditCard, FileText, KeyRound, LifeBuoy, LockKeyhole, Plus, Server, Settings2, ShieldCheck, ToggleLeft, Users, Webhook } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

const usage = [{ label: 'Jan', value: 210 }, { label: 'Feb', value: 260 }, { label: 'Mar', value: 245 }, { label: 'Apr', value: 318 }, { label: 'May', value: 380 }, { label: 'Jun', value: 430 }]
const tickets = [{ id: '#SUP-831', subject: 'Webhook delivery delay', tenant: 'Spice Route', priority: 'High', status: 'Open' }, { id: '#SUP-830', subject: 'Need help with plan upgrade', tenant: 'Bright Future Academy', priority: 'Normal', status: 'Pending' }, { id: '#SUP-829', subject: 'POS terminal setup', tenant: 'The Daily Basket', priority: 'Normal', status: 'Resolved' }]
const activity = [{ text: 'Admin sign-in verified', meta: 'Arjun Kapoor · Mumbai · 2 min ago' }, { text: 'API key rotated', meta: 'Developer console · 34 min ago' }, { text: 'Tenant suspended', meta: 'Pulse Fitness · 1 hr ago' }, { text: 'Team member invited', meta: 'Nisha Verma · 3 hr ago' }]

export function WorkspacePanel({ kind }: { kind: 'billing' | 'support' | 'analytics' | 'security' | 'activity' | 'team' | 'developer' | 'settings' }) {
  const configs = { billing: { eyebrow: 'Workspace / Billing', title: 'Billing & plans', description: 'Revenue operations, plan entitlements, and invoice health.', icon: CreditCard }, support: { eyebrow: 'Workspace / Support', title: 'Support center', description: 'Keep service quality high with a focused queue and clear ownership.', icon: LifeBuoy }, analytics: { eyebrow: 'Insights / Analytics', title: 'Analytics', description: 'Understand activation, retention, and platform usage at a glance.', icon: Activity }, security: { eyebrow: 'Insights / Security', title: 'Security center', description: 'Review access posture, audit trails, and high-signal events.', icon: ShieldCheck }, activity: { eyebrow: 'Insights / Activity', title: 'Platform activity', description: 'A live operational ledger of important changes across RVC.', icon: Activity }, team: { eyebrow: 'Administration / Team', title: 'Team & permissions', description: 'Manage operators and keep privileged access intentional.', icon: Users }, developer: { eyebrow: 'Administration / Developer', title: 'Developer console', description: 'Control API access, webhooks, and platform integration health.', icon: Code2 }, settings: { eyebrow: 'Administration / Settings', title: 'System settings', description: 'Configure workspace defaults and operational guardrails.', icon: Settings2 } }[kind]
  const Icon = configs.icon
  return <div className="space-y-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-primary">{configs.eyebrow}</p><h1 className="mt-1 text-3xl font-bold tracking-tight sm:text-4xl">{configs.title}</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">{configs.description}</p></div><span className="grid size-12 place-items-center rounded-2xl bg-primary/10 text-primary"><Icon className="size-6" /></span></div>{kind === 'billing' && <BillingPanel />}{kind === 'support' && <SupportPanel />}{kind === 'analytics' && <AnalyticsPanel />}{kind === 'security' && <SecurityPanel />}{kind === 'activity' && <ActivityPanel />}{kind === 'team' && <TeamPanel />}{kind === 'developer' && <DeveloperPanel />}{kind === 'settings' && <SettingsPanel />}</div>
}

function BillingPanel() { return <><div className="grid gap-4 sm:grid-cols-3"><MiniStat label="MRR" value="INR 52.4L" trend="+12.8%" /><MiniStat label="Invoices due" value="18" trend="INR 1.2L" /><MiniStat label="Collection rate" value="98.4%" trend="+1.6%" /></div><div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><Panel title="Plan mix"><div className="space-y-4">{[['Starter', '284', 'INR 2.8L', 'bg-slate-400'], ['Growth', '448', 'INR 13.4L', 'bg-primary'], ['Pro', '110', 'INR 11L', 'bg-accent']].map(([name, count, revenue, color]) => <div key={name}><div className="mb-2 flex items-center justify-between text-sm"><span className="font-semibold">{name}</span><span className="text-muted-foreground">{count} tenants · {revenue}</span></div><div className="h-2 rounded-full bg-muted"><div className={`h-full rounded-full ${color}`} style={{ width: `${Math.min(100, Number(count) / 5)}%` }} /></div></div>)}</div></Panel><Panel title="Recent invoices"><div className="space-y-3">{['INV-2048 · INR 9,999 · Paid', 'INV-2047 · INR 2,999 · Paid', 'INV-2046 · INR 999 · Pending'].map((item) => <div key={item} className="flex items-center justify-between rounded-xl bg-muted/40 px-3 py-3 text-sm"><span>{item}</span><FileText className="size-4 text-muted-foreground" /></div>)}</div></Panel></div></> }
function SupportPanel() { const [filter, setFilter] = useState('All'); const shown = tickets.filter((ticket) => filter === 'All' || ticket.status === filter); return <><div className="flex flex-wrap gap-2">{['All', 'Open', 'Pending', 'Resolved'].map((item) => <button key={item} type="button" onClick={() => setFilter(item)} className={`rounded-xl px-3 py-2 text-sm font-semibold ${filter === item ? 'bg-primary text-primary-foreground' : 'border border-border text-muted-foreground hover:bg-muted'}`}>{item}</button>)}</div><Panel title="Support queue"><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="border-b border-border text-xs text-muted-foreground"><tr><th className="pb-3">Ticket</th><th className="pb-3">Tenant</th><th className="pb-3">Priority</th><th className="pb-3">Status</th><th className="pb-3 text-right">Action</th></tr></thead><tbody>{shown.map((ticket) => <tr key={ticket.id} className="border-b border-border/70 last:border-0"><td className="py-4"><p className="font-semibold">{ticket.subject}</p><p className="mt-1 text-xs text-muted-foreground">{ticket.id}</p></td><td className="py-4 text-muted-foreground">{ticket.tenant}</td><td className="py-4"><span className={ticket.priority === 'High' ? 'text-red-500' : 'text-muted-foreground'}>{ticket.priority}</span></td><td className="py-4"><span className="rounded-full bg-primary/10 px-2.5 py-1 text-xs font-semibold text-primary">{ticket.status}</span></td><td className="py-4 text-right"><button type="button" className="rounded-lg px-3 py-2 text-xs font-semibold text-primary hover:bg-primary/10">Open</button></td></tr>)}</tbody></table></div></Panel></> }
function AnalyticsPanel() { return <><div className="grid gap-4 sm:grid-cols-3"><MiniStat label="Activation rate" value="68.4%" trend="+4.2%" /><MiniStat label="30-day retention" value="91.8%" trend="+2.1%" /><MiniStat label="API calls" value="4.8M" trend="+18.6%" /></div><Panel title="Platform usage"><div className="h-80"><ResponsiveContainer width="100%" height="100%"><LineChart data={usage}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="var(--border)" /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fill: 'var(--muted-foreground)', fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fill: 'var(--muted-foreground)', fontSize: 11 }} /><Tooltip contentStyle={{ background: 'var(--card)', border: '1px solid var(--border)', borderRadius: 12 }} /><Line type="monotone" dataKey="value" stroke="#4338ca" strokeWidth={3} dot={{ r: 4, fill: '#4338ca' }} /></LineChart></ResponsiveContainer></div></Panel></> }
function SecurityPanel() { return <><div className="grid gap-4 sm:grid-cols-3"><MiniStat label="Security score" value="94/100" trend="Healthy" /><MiniStat label="MFA coverage" value="87%" trend="+6.4%" /><MiniStat label="Open alerts" value="3" trend="Review" /></div><div className="grid gap-6 xl:grid-cols-2"><Panel title="Control posture">{[['MFA enforced for admins', true], ['Suspicious login detection', true], ['Production secrets rotated', true], ['Quarterly access review', false]].map(([label, value]) => <div key={String(label)} className="flex items-center justify-between border-b border-border/70 py-4 last:border-0"><span className="text-sm font-medium">{String(label)}</span><span className={`inline-flex items-center gap-2 text-xs font-semibold ${value ? 'text-emerald-500' : 'text-amber-500'}`}>{value ? <Check className="size-4" /> : <span className="size-2 rounded-full bg-amber-500" />}{value ? 'Compliant' : 'Needs review'}</span></div>)}</Panel><Panel title="Recent security events">{activity.slice(0, 3).map((item) => <div key={item.text} className="border-b border-border/70 py-4 last:border-0"><p className="text-sm font-semibold">{item.text}</p><p className="mt-1 text-xs text-muted-foreground">{item.meta}</p></div>)}</Panel></div></> }
function ActivityPanel() { return <Panel title="Audit ledger"><div className="space-y-1">{activity.concat(activity).map((item, index) => <div key={`${item.text}-${index}`} className="flex items-start gap-4 border-b border-border/70 py-4 last:border-0"><span className="mt-1 grid size-8 place-items-center rounded-lg bg-primary/10 text-primary"><Activity className="size-4" /></span><div><p className="text-sm font-semibold">{item.text}</p><p className="mt-1 text-xs text-muted-foreground">{item.meta}</p></div><span className="ml-auto text-xs text-muted-foreground">{index + 2}m</span></div>)}</div></Panel> }
function TeamPanel() { return <><div className="flex justify-end"><button type="button" onClick={() => alert('Invite flow opened.')} className="inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground"><Plus className="size-4" /> Invite teammate</button></div><Panel title="Operators"><div className="grid gap-3 md:grid-cols-2">{[['Arjun Kapoor', 'Super Admin', 'AK'], ['Nisha Verma', 'Operations Lead', 'NV'], ['Dev Malhotra', 'Developer', 'DM'], ['Priya Shah', 'Support Manager', 'PS']].map(([name, role, initials]) => <div key={name} className="flex items-center gap-3 rounded-xl border border-border p-4"><span className="grid size-10 place-items-center rounded-full bg-primary/15 text-xs font-bold text-primary">{initials}</span><div><p className="text-sm font-semibold">{name}</p><p className="text-xs text-muted-foreground">{role}</p></div><button type="button" className="ml-auto rounded-lg p-2 text-muted-foreground hover:bg-muted"><ChevronRight className="size-4" /></button></div>)}</div></Panel></> }
function DeveloperPanel() { return <><div className="grid gap-4 sm:grid-cols-3"><MiniStat label="API requests today" value="184k" trend="99.99% success" /><MiniStat label="Active keys" value="12" trend="2 expiring" /><MiniStat label="Webhook delivery" value="99.7%" trend="Healthy" /></div><div className="grid gap-6 xl:grid-cols-2"><Panel title="API access"><Row icon={<KeyRound className="size-4" />} title="Production API keys" detail="12 active keys across 4 services" /><Row icon={<Webhook className="size-4" />} title="Webhook endpoints" detail="28 configured · 1 retrying" /><Row icon={<Server className="size-4" />} title="Environment health" detail="Production and staging operational" /></Panel><Panel title="Quick actions"><button type="button" onClick={() => alert('API key creation flow opened.')} className="flex w-full items-center justify-between rounded-xl border border-border p-4 text-left hover:bg-muted"><span><span className="block text-sm font-semibold">Create API key</span><span className="mt-1 block text-xs text-muted-foreground">Generate scoped credentials</span></span><Plus className="size-4 text-primary" /></button></Panel></div></> }
function SettingsPanel() { const [enabled, setEnabled] = useState(true); return <div className="grid gap-6 xl:grid-cols-2"><Panel title="Workspace defaults"><Row icon={<Settings2 className="size-4" />} title="Default timezone" detail="Asia/Kolkata (IST)" /><Row icon={<FileText className="size-4" />} title="Invoice prefix" detail="RVC-INV" /><Row icon={<LockKeyhole className="size-4" />} title="Session timeout" detail="30 minutes" /></Panel><Panel title="Operational controls"><div className="flex items-center justify-between border-b border-border/70 py-4"><div><p className="text-sm font-semibold">Maintenance mode</p><p className="mt-1 text-xs text-muted-foreground">Prevent new tenant actions while enabled.</p></div><button type="button" onClick={() => setEnabled(!enabled)} className={`rounded-full p-1 transition-colors ${enabled ? 'bg-primary' : 'bg-muted'}`}><span className={`block size-5 rounded-full bg-background transition-transform ${enabled ? 'translate-x-5' : ''}`} /></button></div><div className="flex items-center justify-between py-4"><div><p className="text-sm font-semibold">Audit logging</p><p className="mt-1 text-xs text-muted-foreground">Required for all admin actions.</p></div><span className="text-xs font-semibold text-emerald-500">Enabled</span></div></Panel></div> }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-border bg-card p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><h2 className="text-sm font-semibold">{title}</h2><button type="button" className="rounded-lg p-2 text-muted-foreground hover:bg-muted"><ChevronRight className="size-4" /></button></div>{children}</section> }
function MiniStat({ label, value, trend }: { label: string; value: string; trend: string }) { return <div className="rounded-2xl border border-border bg-card p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p><p className="mt-2 text-xs font-semibold text-emerald-500">{trend}</p></div> }
function Row({ icon, title, detail }: { icon: React.ReactNode; title: string; detail: string }) { return <div className="flex items-center gap-3 border-b border-border/70 py-4 last:border-0"><span className="grid size-9 place-items-center rounded-lg bg-primary/10 text-primary">{icon}</span><div><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div><ChevronRight className="ml-auto size-4 text-muted-foreground" /></div> }
